# Copyright (c) 2024, 2025 acrion innovations GmbH
# Authors: Stefan Zipproth, s.zipproth@acrion.ch
#
# This file is part of Ditana Installer, see
# https://github.com/acrion/ditana-installer and https://ditana.org/installer.
#
# Ditana Installer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ditana Installer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ditana Installer. If not, see <https://www.gnu.org/licenses/>.

---
- hosts: localhost
  connection: local
  tasks:
  - name: Enable Arch multilib repo if enable_multilib is y
    replace:
      path: /etc/pacman.conf
      regexp: '^\s*#?\s*\[multilib\]\s*\n\s*#?\s*Include\s*=\s*/etc/pacman.d/mirrorlist'
      replace: '\n[multilib]\nInclude = /etc/pacman.d/mirrorlist'
    when: enable_multilib == "y"
